### ISSUE TITLE
Is using reflection int Unity3d decrease the performance?

### ISSUE THREAD

**Issue by MEyes** [jbruening/ugui-mvvm#1]
hi jbruening,
I looked at your code,there are many reflection .
Is using reflection int Unity3d decrease the performance?
thx :)

**Comment by jbruening** [comment]
Yes, it uses reflection. To reduce it, propertyinfos are cached on awake for DataContext and INPCBinding, and there is some additional processing relegated to editor build-time for the CommandBinding.  Most of the real cost comes from the use of GetValue and SetValue when properties are changed.

Again, though, this is only when the properties are changed, which also only happens if the classes with those properties implement INotifyPropertyChanged. If they don't, then the properties are only gotten once.

While slow, it is [plenty fast](https://lotsacode.wordpress.com/2010/04/12/getting-data-through-reflection-getvalue/) for a standard user interface, as people are slow when it comes to typing, clicking buttons, etc - things that happen less than once per frame.  Do not use it to do something like binding to an object's position that is updated every frame.

**Comment by jbruening** [comment]
commit e63bd8d now also addresses this via giving you the option of generating property accessor functions.

**Comment by MEyes** [comment]
cool
