### ISSUE TITLE
Getting errors in the example scene

### ISSUE THREAD

**Issue by nanoziros** [jbruening/ugui-mvvm#2]
Could not get event m_OnValueChange on UnityEngine.UI.InputField
UnityEngine.Debug:LogErrorFormat(String, Object[])
INPCBindingEditor:GetEvent(Component, SerializedProperty) (at Assets/Packages/MVVM/ugui-mvvm/Editor/INPCBindingEditor.cs:82)
INPCBindingEditor:FigureViewBinding(INPCBinding) (at Assets/Packages/MVVM/ugui-mvvm/Editor/INPCBindingEditor.cs:46)
INPCBindingEditor:FigureViewBindings() (at Assets/Packages/MVVM/ugui-mvvm/Editor/INPCBindingEditor.cs:28)
INPCBindingEditor:OnPostProcessScene() (at Assets/Packages/MVVM/ugui-mvvm/Editor/INPCBindingEditor.cs:18)

**Comment by jbruening** [comment]
Are you referring to the Demo.unity scene? What version of unity are you using?

Neither scene is throwing this error. Unity 5.2.1f1

**Comment by autukill** [comment]
Demo is throwing this error. Unity 5.3.5f1

**Comment by jbruening** [comment]
This issue is not permanently fixable.  The reason it is happening is because unity changed the field name, but there's no way I can see to get at the FormerlySerializedAs attribute on a SerializedProperty in order to handle them changing the names of things.

This is 'fixable' by just re-setting the value in the event drop down on the INPCBinding.
